version: '3.8'

services:
  viaggiviajesyturismo:
    container_name: viaggiviajesyturismo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11.10
    container_name: viaggiviajesyturismo_db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: t00r
      MYSQL_DATABASE: viaggiviajesyturismo
      MYSQL_USER: user
      MYSQL_PASSWORD: t00r
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api/scripts/u275597130_viaggi.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
